### ISSUE TITLE
Need a GUI

### ISSUE THREAD

**Issue by Wabri** [Wabri/YAPI#23]
An example:

![something](https://user-images.githubusercontent.com/12409541/49589763-7f285780-f96a-11e8-9728-6cd67bace9f2.png)

It doesn't have to be exactly like that, but these components are definitely necessary:
- packages list
- a list of commands
- an output
- an input field

**Comment by IanDuncanT** [comment]
First Version in #26

**Comment by IanDuncanT** [comment]
Are there any options to use in the gui version? The only current ones are install and console, which are for a terminal program.

**Comment by IanDuncanT** [comment]
![image](https://user-images.githubusercontent.com/39711921/49660365-037ee700-fa0c-11e8-8bd9-1512f6e3ce5f.png)
Is this a good form? The bottom left is the output text.

**Comment by Wabri** [comment]
I think the best way is to run the gui version without args

**Comment by Wabri** [comment]
That gui is perfect, but maybe don't print the test script in the list of packages.

**Comment by IanDuncanT** [comment]
I have finished this in my pull request, but it does not close the bash and shell installers
