### ISSUE TITLE
Create Shell and Bash Package Installer

### ISSUE THREAD

**Issue by IanDuncanT** [Wabri/YAPI#27]
Create a bash and shell script to do "yapi install test" to install a package named test and such.

**Comment by IanDuncanT** [comment]
It is not working currently, so that will not be the final version of it in pull request 26.

**Comment by IanDuncanT** [comment]
Still need to work on this. It is not currently working.

**Comment by Wabri** [comment]
now it works, less problematic than it seems:
https://github.com/Wabri/YAPI/blob/97ccb0375036039db89626a219023501602ffafb/yapi.sh#L1
